#!/usr/bin/python3

import sys
import time 
import RPi.GPIO as GPIO

class Unbuffered(object):
   def __init__(self, stream):
       self.stream = stream
   def write(self, data):
       self.stream.write(data)
       self.stream.flush()
   def writelines(self, datas):
       self.stream.writelines(datas)
       self.stream.flush()
   def __getattr__(self, attr):
       return getattr(self.stream, attr)

sys.stdout = Unbuffered(sys.stdout)

GPIO.setmode(GPIO.BCM)
GPIO.setup(0, GPIO.IN, pull_up_down=GPIO.PUD_UP)
GPIO.add_event_detect(0, GPIO.RISING)

def button_press_callback(f):
    print("0")

GPIO.add_event_callback(0, button_press_callback)

while(True):
    time.sleep(0.1)
